# Generated by Django 4.1 on 2022-08-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("gender", models.IntegerField(default=0)),
                ("age", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                ("description", models.CharField(max_length=100)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
