# Generated by Django 4.1 on 2022-09-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('name', 'gender', 'age')},
        ),
        migrations.AlterModelTable(
            name='info',
            table='users_info',
        ),
    ]
